name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy-to-huggingface:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repo
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config --global user.email "mohammed.aswath07@gmail.com"
          git config --global user.name "Mohammed Aswath"

      - name: Clone Hugging Face Repo
        run: |
          git clone https://MohammedAswath:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/MohammedAswath/mlops-crop-predictor hf-space

      - name: Copy files to Hugging Face repo
        run: |
          shopt -s extglob
          cp -r !(hf-space) hf-space/

      - name: Commit and Push to Hugging Face
        run: |
          cd hf-space
          git add .
          git commit -m "🚀 Auto sync from GitHub" || echo "No changes to commit"
          git push
