name: Push to Hugging Face Space

on:
  push:
    branches:
      - main  # or master if that's your default branch

jobs:
  deploy-to-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "mohammed.aswath07@gmail.com"
          git config --global user.name "Mohammed-Aswath"

      - name: Push to Hugging Face Space
        run: |
          git clone https://MohammedAswath:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/MohammedAswath/mlops-crop-predictor
          cp -r ./* mlops-crop-predictor/
          cd mlops-crop-predictor
          git add .
          git commit -m "🚀 Auto sync from GitHub"
          git push
