name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repo
        uses: actions/checkout@v3

      - name: Set Git Identity
        run: |
          git config --global user.email "mohammed.aswath07@gmail.com"
          git config --global user.name "MohammedAswath"

      - name: Clone Hugging Face Space
        run: |
          git clone https://MohammedAswath:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/MohammedAswath/mlops-crop-predictor hf-space

      - name: Copy Code to Hugging Face Space (excluding hf-space)
        run: |
          rsync -av --exclude=hf-space ./ hf-space/
          cd hf-space
          git add .
          git commit -m "🚀 Auto sync from GitHub" || echo "No changes to commit"
          git push
